import type { Company } from "./types";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "c001",
    name: "Meridian AI",
    domain: "meridian.ai",
    stage: "Seed",
    sector: "AI Infrastructure",
    tags: ["LLM", "DevTools", "B2B SaaS"],
    location: "San Francisco, CA",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Meridian builds context-aware LLM middleware that lets enterprises safely plug proprietary data into foundation models without exposing raw records. Their semantic firewall layer handles PII stripping and access scoping at inference time.",
    thesisScore: 94,
    thesisReasons: [
      "Enterprise AI security is a top-3 fund theme",
      "Technical founders ex-Google Brain + Stripe",
      "Revenue-generating at Seed — rare signal",
      "Solves a critical compliance gap in every LLM deployment",
    ],
    signals: [
      {
        id: "s1",
        type: "funding",
        title: "Raised $4.2M Seed from Sequoia Arc",
        date: "2024-11-01",
        source: "TechCrunch",
      },
      {
        id: "s2",
        type: "hiring",
        title: "Opened 3 senior ML engineer roles",
        date: "2025-01-15",
      },
      {
        id: "s3",
        type: "product",
        title: "Launched v2 with audit trail dashboard",
        date: "2025-02-10",
      },
    ],
    lastActivity: "2025-02-10",
    fundingTotal: "$4.2M",
  },
  {
    id: "c002",
    name: "Cartograph",
    domain: "cartograph.dev",
    stage: "Series A",
    sector: "Developer Tools",
    tags: ["Observability", "Platform Engineering", "Open Source"],
    location: "New York, NY",
    foundedYear: 2022,
    employees: "51-200",
    description:
      "Cartograph provides a unified dependency and service map for modern engineering orgs. Think Datadog + Notion for platform teams — every service, owner, SLA, and incident history in one queryable graph.",
    thesisScore: 81,
    thesisReasons: [
      "Platform engineering category growing 40% YoY",
      "Strong OSS flywheel (8k GitHub stars in 14 months)",
      "Land-and-expand motion proven in mid-market",
    ],
    signals: [
      {
        id: "s4",
        type: "funding",
        title: "Raised $18M Series A led by Accel",
        date: "2024-09-12",
        source: "Forbes",
      },
      {
        id: "s5",
        type: "press",
        title: "Named to Forbes Cloud 100 Rising Stars",
        date: "2024-12-01",
      },
    ],
    lastActivity: "2024-12-01",
    fundingTotal: "$22M",
  },
  {
    id: "c003",
    name: "Vantage Health",
    domain: "vantagehealth.com",
    stage: "Pre-seed",
    sector: "Digital Health",
    tags: ["Mental Health", "AI Therapy", "Consumer"],
    location: "Austin, TX",
    foundedYear: 2024,
    employees: "1-10",
    description:
      "Vantage delivers evidence-based CBT programs through conversational AI tailored to each user's therapy history and mood patterns. Licensed therapist oversight baked in for safety and regulatory compliance.",
    thesisScore: 67,
    thesisReasons: [
      "Mental health demand is structurally under-served",
      "Regulatory risk adds uncertainty at this stage",
    ],
    signals: [
      {
        id: "s6",
        type: "founder",
        title: "CEO previously built + sold Calm competitor (Headspace rival)",
        date: "2024-08-20",
      },
    ],
    lastActivity: "2024-08-20",
    fundingTotal: undefined,
  },
  {
    id: "c004",
    name: "Fluxor",
    domain: "fluxor.io",
    stage: "Seed",
    sector: "Fintech",
    tags: ["Treasury", "CFO Suite", "B2B SaaS"],
    location: "London, UK",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Fluxor automates cash flow forecasting for mid-market CFOs by integrating with ERP, banking, and AR/AP systems. ML engine learns seasonal patterns and builds scenario models in real time.",
    thesisScore: 88,
    thesisReasons: [
      "CFO tooling is an active fund theme post-ZIRP",
      "10x faster implementation vs legacy vendors (NetSuite, Kyriba)",
      "Strong NRR: 138% in pilot cohort",
    ],
    signals: [
      {
        id: "s7",
        type: "hiring",
        title: "Hiring VP Sales (first commercial hire)",
        date: "2025-01-28",
      },
      {
        id: "s8",
        type: "product",
        title: "SAP integration shipped",
        date: "2025-02-05",
      },
    ],
    lastActivity: "2025-02-05",
    fundingTotal: "$3.8M",
  },
  {
    id: "c005",
    name: "Latent Space",
    domain: "latentspace.so",
    stage: "Pre-seed",
    sector: "AI Infrastructure",
    tags: ["Vector DB", "RAG", "Open Source"],
    location: "Remote",
    foundedYear: 2024,
    employees: "1-10",
    description:
      "Latent Space is an open-source vector database purpose-built for multi-modal embeddings. Benchmarks show 3x throughput over Weaviate on image+text hybrid queries, with zero-config partitioning.",
    thesisScore: 76,
    thesisReasons: [
      "Infra layer bets often compound well",
      "OSS with GitHub traction (2.1k stars in 8 weeks)",
      "No clear monetization path yet",
    ],
    signals: [
      {
        id: "s9",
        type: "product",
        title: "v0.4 shipped with GPU-native index compression",
        date: "2025-02-12",
      },
    ],
    lastActivity: "2025-02-12",
  },
  {
    id: "c006",
    name: "Aurelius",
    domain: "aurelius.app",
    stage: "Series A",
    sector: "Legal Tech",
    tags: ["AI Contracts", "CLM", "Enterprise"],
    location: "Chicago, IL",
    foundedYear: 2021,
    employees: "51-200",
    description:
      "Aurelius is an AI contract lifecycle management platform. Automates redlining, clause extraction, and risk scoring — reducing outside counsel spend by 40%+ for F500 legal teams.",
    thesisScore: 72,
    thesisReasons: [
      "Enterprise CLM market validated with incumbents (Ironclad, ContractPodAi)",
      "Differentiated on compliance audit trails",
      "Slightly late to a competitive category",
    ],
    signals: [
      {
        id: "s10",
        type: "press",
        title: "Partnership with Salesforce AppExchange",
        date: "2025-01-10",
      },
    ],
    lastActivity: "2025-01-10",
    fundingTotal: "$15M",
  },
  {
    id: "c007",
    name: "Nomad Protocol",
    domain: "nomadprotocol.xyz",
    stage: "Seed",
    sector: "Web3",
    tags: ["DeFi", "Cross-chain", "Infrastructure"],
    location: "Singapore",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Nomad Protocol enables atomic cross-chain liquidity routing without wrapped assets. Their solver network finds optimal paths across 14 EVM and non-EVM chains with sub-second settlement.",
    thesisScore: 55,
    thesisReasons: [
      "Web3 infrastructure outside current thesis",
      "Strong technical team",
      "Market timing uncertainty",
    ],
    signals: [
      {
        id: "s11",
        type: "funding",
        title: "$6M raised from Paradigm and a16z crypto",
        date: "2024-10-30",
      },
    ],
    lastActivity: "2024-10-30",
    fundingTotal: "$6M",
  },
  {
    id: "c008",
    name: "Cobalt Robotics",
    domain: "cobaltrobotics.com",
    stage: "Series B",
    sector: "Robotics",
    tags: ["Warehouse Automation", "Computer Vision", "Deep Tech"],
    location: "San Jose, CA",
    foundedYear: 2020,
    employees: "201-500",
    description:
      "Cobalt builds autonomous mobile robots for warehouse inspection and security. Fleet of 500+ deployed units across 3PL and e-commerce DCs, with 99.3% uptime SLA.",
    thesisScore: 83,
    thesisReasons: [
      "Physical AI is a core emerging theme",
      "Proven unit economics at scale",
      "Labor cost arbitrage is durable",
    ],
    signals: [
      {
        id: "s12",
        type: "funding",
        title: "Series B extension: $30M from Tiger Global",
        date: "2024-12-15",
      },
    ],
    lastActivity: "2024-12-15",
    fundingTotal: "$72M",
  },
  {
    id: "c009",
    name: "Helix Bio",
    domain: "helixbio.co",
    stage: "Seed",
    sector: "Biotech",
    tags: ["Drug Discovery", "AI", "Protein Folding"],
    location: "Boston, MA",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Helix Bio uses diffusion models trained on protein-ligand interaction data to propose novel small-molecule candidates, cutting wet-lab iteration cycles from months to days.",
    thesisScore: 79,
    thesisReasons: [
      "AI-bio convergence is a key thesis pillar",
      "AlphaFold-era tailwinds",
      "Long path to revenue — needs bio partner to validate",
    ],
    signals: [
      {
        id: "s13",
        type: "product",
        title: "First IP filing: novel KRAS inhibitor scaffold",
        date: "2025-01-22",
      },
    ],
    lastActivity: "2025-01-22",
    fundingTotal: "$5M",
  },
  {
    id: "c010",
    name: "Kernel",
    domain: "kernel.finance",
    stage: "Series A",
    sector: "Fintech",
    tags: ["Embedded Finance", "Banking-as-a-Service", "API"],
    location: "Miami, FL",
    foundedYear: 2021,
    employees: "51-200",
    description:
      "Kernel provides a single API for software companies to embed bank accounts, cards, and lending into their products. Processes $2B+ annualized GMV with 180+ active platform customers.",
    thesisScore: 86,
    thesisReasons: [
      "Embedded finance still early in vertical SaaS adoption curve",
      "Strong revenue base ($8M ARR)",
      "Differentiated on real-time ledger architecture",
    ],
    signals: [
      {
        id: "s14",
        type: "hiring",
        title: "Headcount grew 40% in Q4 2024",
        date: "2025-01-05",
      },
    ],
    lastActivity: "2025-01-05",
    fundingTotal: "$24M",
  },
  {
    id: "c011",
    name: "Orion Fleet",
    domain: "orionfleet.ai",
    stage: "Pre-seed",
    sector: "Climate Tech",
    tags: ["EV", "Fleet Management", "SMB"],
    location: "Denver, CO",
    foundedYear: 2024,
    employees: "1-10",
    description:
      "Orion helps small-business fleet operators transition to EVs with AI-optimized charging schedules, utility rebate discovery, and vehicle financing integrations — all in one dashboard.",
    thesisScore: 71,
    thesisReasons: [
      "Climate mandate tailwinds for fleet electrification",
      "SMB focus limits initial deal size",
      "Founder has deep fleet-ops background (ex-Lytx)",
    ],
    signals: [
      {
        id: "s15",
        type: "founder",
        title: "Accepted into Y Combinator W25",
        date: "2025-01-06",
      },
    ],
    lastActivity: "2025-01-06",
  },
  {
    id: "c012",
    name: "Patchwork Security",
    domain: "patchwork.security",
    stage: "Seed",
    sector: "Cybersecurity",
    tags: ["AppSec", "AI-Powered", "SDLC"],
    location: "Seattle, WA",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Patchwork integrates into CI/CD pipelines to detect and auto-remediate vulnerabilities using AI-generated patches verified by a sandboxed test runner — reducing mean-time-to-fix from 47 days to under 4 hours.",
    thesisScore: 92,
    thesisReasons: [
      "Security is a perennial fund theme",
      "Developer-first motion with measurable ROI",
      "GitHub integration creates high-stickiness distribution",
      "Team: ex-Snyk CTO + ex-GitHub Security lead",
    ],
    signals: [
      {
        id: "s16",
        type: "product",
        title: "Rust & Go support launched",
        date: "2025-02-01",
      },
      {
        id: "s17",
        type: "hiring",
        title: "Hiring DevRel lead",
        date: "2025-02-14",
      },
    ],
    lastActivity: "2025-02-14",
    fundingTotal: "$5.5M",
  },
  {
    id: "c013",
    name: "Sylvan Data",
    domain: "sylvandata.io",
    stage: "Series A",
    sector: "Data & Analytics",
    tags: ["Data Catalog", "Governance", "AI-native"],
    location: "San Francisco, CA",
    foundedYear: 2022,
    employees: "51-200",
    description:
      "Sylvan is an AI-native data catalog that auto-classifies tables, infers lineage, and generates natural language documentation. Competes on ease-of-deployment vs. Collibra and Alation.",
    thesisScore: 77,
    thesisReasons: [
      "Data governance demand accelerating with AI adoption",
      "Good NRR (121%)",
      "Sales cycle can be long in data infra",
    ],
    signals: [
      {
        id: "s18",
        type: "press",
        title: "Gartner Cool Vendor 2024 recognition",
        date: "2024-11-18",
      },
    ],
    lastActivity: "2024-11-18",
    fundingTotal: "$19M",
  },
  {
    id: "c014",
    name: "Glyph Education",
    domain: "glyphedu.com",
    stage: "Pre-seed",
    sector: "EdTech",
    tags: ["K-12", "AI Tutoring", "Literacy"],
    location: "Atlanta, GA",
    foundedYear: 2024,
    employees: "1-10",
    description:
      "Glyph uses adaptive AI to accelerate reading fluency in K-5 students, delivered through schools with a per-seat SaaS model. Early pilots show 2.3x improvement in Lexile score vs. control groups.",
    thesisScore: 68,
    thesisReasons: [
      "EdTech adoption is slow in public school systems",
      "Strong outcome data from pilot",
      "Founder background in literacy research",
    ],
    signals: [
      {
        id: "s19",
        type: "product",
        title: "Pilot expanded to 12 districts in Georgia",
        date: "2025-01-30",
      },
    ],
    lastActivity: "2025-01-30",
  },
  {
    id: "c015",
    name: "Epoch Manufacturing",
    domain: "epochmfg.com",
    stage: "Seed",
    sector: "Industrial Tech",
    tags: ["Digital Twin", "Predictive Maintenance", "IIoT"],
    location: "Detroit, MI",
    foundedYear: 2022,
    employees: "11-50",
    description:
      "Epoch installs sensor kits on legacy factory equipment and builds digital twin models to predict failures before they occur, reducing unplanned downtime by 60-80% for automotive OEM customers.",
    thesisScore: 80,
    thesisReasons: [
      "Industrial AI has a massive greenfield in legacy OEM base",
      "Hardware + software model creates high switching costs",
      "Signed LOI with Tier-1 auto supplier",
    ],
    signals: [
      {
        id: "s20",
        type: "funding",
        title: "Raised $7M Seed from Lux Capital",
        date: "2025-01-20",
      },
    ],
    lastActivity: "2025-01-20",
    fundingTotal: "$7M",
  },
  {
    id: "c016",
    name: "Spectra Markets",
    domain: "spectramarkets.com",
    stage: "Series B",
    sector: "Fintech",
    tags: ["FX Trading", "Institutional", "AI Execution"],
    location: "New York, NY",
    foundedYear: 2019,
    employees: "201-500",
    description:
      "Spectra provides institutional FX execution with AI-optimized order routing that minimizes market impact. Handles $50B+ monthly volume across 35 currency pairs for hedge funds and banks.",
    thesisScore: 62,
    thesisReasons: [
      "Revenue scale is impressive",
      "Institutional FX is outside primary focus",
      "High regulatory complexity",
    ],
    signals: [
      { id: "s21", type: "press", title: "Featured in Bloomberg Markets", date: "2024-12-10" },
    ],
    lastActivity: "2024-12-10",
    fundingTotal: "$95M",
  },
  {
    id: "c017",
    name: "Terraform Space",
    domain: "terraform.space",
    stage: "Seed",
    sector: "Space Tech",
    tags: ["Satellite", "Edge Computing", "Defense"],
    location: "Huntsville, AL",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Terraform builds edge compute modules for LEO satellites, enabling on-orbit AI inference for Earth observation and signals intelligence applications. First customer is a defense prime contractor.",
    thesisScore: 73,
    thesisReasons: [
      "Dual-use space tech is an emerging category",
      "DoD contract provides revenue visibility",
      "Technically differentiated, small TAM initially",
    ],
    signals: [
      {
        id: "s22",
        type: "product",
        title: "First module successfully deployed on SpaceX Transporter-12",
        date: "2025-01-14",
      },
    ],
    lastActivity: "2025-01-14",
    fundingTotal: "$8M",
  },
  {
    id: "c018",
    name: "Verdant Agri",
    domain: "verdantagri.com",
    stage: "Pre-seed",
    sector: "AgTech",
    tags: ["Precision Agriculture", "AI", "Soil Health"],
    location: "Des Moines, IA",
    foundedYear: 2024,
    employees: "1-10",
    description:
      "Verdant provides AI-powered soil microbiome analysis from farmer-collected samples, generating hyper-local recommendations for fertilizer application that improve yield 15% while cutting input costs.",
    thesisScore: 65,
    thesisReasons: [
      "Climate-adjacent but outside core thesis",
      "Interesting founder (soil scientist from Iowa State)",
      "Go-to-market through ag retailers is unproven",
    ],
    signals: [
      {
        id: "s23",
        type: "founder",
        title: "Joined Ag Startup Engine accelerator",
        date: "2025-02-03",
      },
    ],
    lastActivity: "2025-02-03",
  },
  {
    id: "c019",
    name: "Onyx Commerce",
    domain: "onyxcommerce.io",
    stage: "Series A",
    sector: "E-commerce",
    tags: ["Headless Commerce", "B2B", "Composable"],
    location: "Stockholm, Sweden",
    foundedYear: 2021,
    employees: "51-200",
    description:
      "Onyx is a headless commerce platform purpose-built for B2B manufacturers doing direct-to-buyer sales. Handles complex pricing rules, quote workflows, and ERP integrations that Shopify can't address.",
    thesisScore: 85,
    thesisReasons: [
      "B2B commerce digitization is a strong theme",
      "Wins against BigCommerce and custom builds",
      "European pedigree with North America expansion underway",
    ],
    signals: [
      {
        id: "s24",
        type: "funding",
        title: "Raised €15M Series A from EQT Ventures",
        date: "2024-10-22",
      },
    ],
    lastActivity: "2024-10-22",
    fundingTotal: "€17M",
  },
  {
    id: "c020",
    name: "Lighthouse Analytics",
    domain: "lighthouseanalytics.ai",
    stage: "Seed",
    sector: "AI Infrastructure",
    tags: ["LLM Evaluation", "MLOps", "Enterprise"],
    location: "San Francisco, CA",
    foundedYear: 2023,
    employees: "11-50",
    description:
      "Lighthouse provides automated evaluation suites for LLM-powered products — covering accuracy, hallucination rate, latency, and cost regression in a single CI/CD-integrated dashboard.",
    thesisScore: 90,
    thesisReasons: [
      "LLMOps is a critical emerging category",
      "Every AI team needs evals but none want to build them",
      "Technical founders with prior MLOps exits",
      "Strong word-of-mouth among ML engineers",
    ],
    signals: [
      {
        id: "s25",
        type: "product",
        title: "Anthropic integration launched",
        date: "2025-02-08",
      },
      {
        id: "s26",
        type: "hiring",
        title: "Opened 5 eng roles across ML and backend",
        date: "2025-02-15",
      },
    ],
    lastActivity: "2025-02-15",
    fundingTotal: "$4.8M",
  },
];

export const SECTORS = Array.from(new Set(MOCK_COMPANIES.map((c) => c.sector))).sort();
export const STAGES = ["Pre-seed", "Seed", "Series A", "Series B", "Series C+"];
